image: "rust:1.61-buster"

stages:
  - lintertest
  - build
  - deploy

before_script:
    - cp "$CI_SERVER_TLS_CA_FILE" ./gitlab_ca.crt
    - git config --global credential.helper store
    - echo "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.tetrane.vpn" > ~/.git-credentials
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.tetrane.vpn/".insteadOf ssh://git@gitlab.tetrane.vpn/
    - rustc --version
    - export GIT_SSL_CAINFO="$CI_SERVER_TLS_CA_FILE"
    - export CARGO_NET_GIT_FETCH_WITH_CLI=true

clippy:
  stage: lintertest
  script:
    - rustup component add rustfmt --toolchain 1.61.0-x86_64-unknown-linux-gnu
    - rustup component add clippy --toolchain 1.61.0-x86_64-unknown-linux-gnu
    - cargo fmt -- --check
    - RUSTFLAGS="-D warnings" cargo clippy
    - RUSTFLAGS="-D warnings" cargo test -- --nocapture

build:
  stage: build
  script:
    - apt update && apt install -y gcc-mingw-w64-x86-64
    - rustup target add x86_64-pc-windows-gnu
    - RUSTFLAGS="-D warnings" cargo build --release
    - RUSTFLAGS="-D warnings" cargo build --release --target x86_64-pc-windows-gnu
  artifacts:
    paths:
      - target/release/checkout
      - target/x86_64-pc-windows-gnu/release/checkout.exe

